version: "3"
services:
  logitechmediaserver:
    #container_name: "lms-dev"
    hostname: lms-docker
    image: merikz/docker-logitechmediaserver:dev
    restart: always
    ports:
      - 3483:3483
      - 9000:9000
      - 9010:9010
      - 9090:9090
    volumes:
      - /srv/music/:/mnt/music
      - /srv/music/lms-playlists:/mnt/playlists
      - logitechmediaserver_state:/mnt/state

volumes:
  logitechmediaserver_state: