#!/bin/bash
#This is called to override the build step at hub.docker/cloud.docker
#At local buile, the Makefile calls this for the actual build, with EXTRAARGS.
set -xe

EXTRAARGS="$@"
LMS_LATEST=$(curl "http://www.mysqueezebox.com/update/?version=7.9.0&revision=1&geturl=1&os=deb")
NEWTAG=$( echo $LMS_LATEST | sed -e s/[^_]*_// | sed -e s/_all.deb// | sed -e s/~/-/)
REGISTRY_USER=merikz
REPOSITORY=docker-logitechmediaserver

docker build \
    $EXTRAARGS \
	 --build-arg LMS_URL=$LMS_LATEST --build-arg LMS_VERSION=$NEWTAG  \
	 .
