#!/bin/bash
#This is called to override the build step at hub.docker/cloud.docker
#At local build, the Makefile calls this for the actual build.
set -xe
REGISTRY_USER=merikz
REPOSITORY=docker-logitechmediaserver
LMS_UID=${LMS_UID:-1000}	#Userid for lms daemon, for access to music files
LMS_VERSION_CHECK_URL=${LMS_VERSION_CHECK_URL:-"http://www.mysqueezebox.com/update/?version=7.9.0&revision=1&geturl=1&os=deb"}

LMS_LATEST=$(curl "$LMS_VERSION_CHECK_URL")
NEWTAG=$( echo ${LMS_LATEST##*/} | sed -e s/[^_]*_// | sed -e s/_all.deb// | sed -e s/~/-/ )

if [ $SOURCE_BRANCH != "master" ]; then
	TAGDEV="${SOURCE_BRANCH}_"
fi

docker build \
	--tag $REGISTRY_USER/$REPOSITORY:$DOCKER_TAG \
	--tag $REGISTRY_USER/$REPOSITORY:"$TAGDEV"$NEWTAG \
	--build-arg LMS_URL=$LMS_LATEST \
	--build-arg LMS_VERSION=$NEWTAG  \
	--build-arg LMS_UID=$LMS_UID \
	.
